package com.cryptum.auth

import android.content.Context
import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Stores the OAuth refresh token encrypted under a key that never leaves the
 * Android Keystore.
 *
 * The refresh token is the most valuable secret on the device: it mints access
 * tokens, and an access token unwraps DEKs. Plain `SharedPreferences` would put
 * it in a file readable by anyone with root, a backup, or a debuggable build
 * (security-requirements).
 *
 * The ciphertext still lives in `SharedPreferences`, and that is fine: without
 * the Keystore key it is inert, and the key is non-exportable and bound to this
 * device's hardware where the hardware supports it.
 */
class KeystoreTokenStore(context: Context) {

    private val prefs = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)

    /** Encrypts [token] and replaces whatever was stored before. */
    fun saveRefreshToken(token: String) {
        val cipher = Cipher.getInstance(TRANSFORMATION).apply {
            init(Cipher.ENCRYPT_MODE, orCreateSecretKey())
        }

        // The IV is generated by the Keystore, not by us. Supplying our own for
        // an AndroidKeyStore key is rejected outright, which is the platform
        // enforcing the rule GCM cares about most: never reuse an IV.
        val iv = cipher.iv
        val ciphertext = cipher.doFinal(token.toByteArray(Charsets.UTF_8))

        prefs.edit()
            .putString(KEY_IV, Base64.encodeToString(iv, Base64.NO_WRAP))
            .putString(KEY_CIPHERTEXT, Base64.encodeToString(ciphertext, Base64.NO_WRAP))
            .commit()
    }

    /**
     * Returns the stored token, or null if there is none, if the ciphertext has
     * been tampered with, or if the key has been invalidated.
     *
     * Null rather than an exception on tamper: every one of those cases has the
     * same correct response — re-authenticate. A caller forced to distinguish
     * them would end up treating them identically anyway, with more code.
     */
    fun refreshToken(): String? {
        val iv = prefs.getString(KEY_IV, null)?.let { Base64.decode(it, Base64.NO_WRAP) } ?: return null
        val ciphertext = prefs.getString(KEY_CIPHERTEXT, null)
            ?.let { Base64.decode(it, Base64.NO_WRAP) } ?: return null
        val key = loadSecretKey() ?: return null

        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION).apply {
                init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(TAG_LENGTH_BITS, iv))
            }
            String(cipher.doFinal(ciphertext), Charsets.UTF_8)
        } catch (_: Exception) {
            null
        }
    }

    /**
     * Removes the token and destroys the key.
     *
     * The key goes too, deliberately. Deleting only the ciphertext would leave a
     * key that could still decrypt a copy recovered from a backup; destroying
     * it makes every copy inert at once — the same crypto-shred argument as
     * ADR-0003, applied on the device.
     */
    fun clear() {
        prefs.edit().clear().commit()
        runCatching { keystore().deleteEntry(KEY_ALIAS) }
    }

    /** Test seam: flips a byte of the stored ciphertext to simulate tampering. */
    internal fun corruptStoredCiphertextForTest() {
        val stored = prefs.getString(KEY_CIPHERTEXT, null) ?: return
        val bytes = Base64.decode(stored, Base64.NO_WRAP)
        bytes[0] = (bytes[0].toInt() xor 0x01).toByte()
        prefs.edit().putString(KEY_CIPHERTEXT, Base64.encodeToString(bytes, Base64.NO_WRAP)).commit()
    }

    private fun orCreateSecretKey(): SecretKey = loadSecretKey() ?: createSecretKey()

    private fun createSecretKey(): SecretKey {
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE)

        val spec = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(KEY_SIZE_BITS)
            // Not gated on biometrics, and this is the module's one deliberate
            // security-for-function trade. Silent refresh must work while the
            // app is backgrounded or locked; requiring user presence here would
            // make background refresh fail in a way indistinguishable from a
            // server fault. The app lock (task 2.12) gates the UI instead.
            .setUserAuthenticationRequired(false)
            .apply {
                // StrongBox is a separate security chip. Where it exists the key
                // is out of reach even of a fully compromised kernel.
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                    setIsStrongBoxBacked(true)
                }
            }
            .build()

        return try {
            generator.init(spec)
            generator.generateKey()
        } catch (_: Exception) {
            // Most devices have no StrongBox, and asking for it there throws.
            // Falling back is correct — the key is still Keystore-backed and
            // non-exportable, which is the guarantee this class actually makes.
            generator.init(
                KeyGenParameterSpec.Builder(
                    KEY_ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                )
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .setKeySize(KEY_SIZE_BITS)
                    .setUserAuthenticationRequired(false)
                    .build(),
            )
            generator.generateKey()
        }
    }

    companion object {
        private const val KEYSTORE = "AndroidKeyStore"
        private const val KEY_ALIAS = "cryptum.refresh-token"
        private const val PREFS = "cryptum.auth"
        private const val KEY_IV = "iv"
        private const val KEY_CIPHERTEXT = "ciphertext"
        private const val KEY_SIZE_BITS = 256
        private const val TAG_LENGTH_BITS = 128
        private const val TRANSFORMATION = "AES/GCM/NoPadding"

        private fun keystore(): KeyStore = KeyStore.getInstance(KEYSTORE).apply { load(null) }

        /** The Keystore key, or null if it has not been created yet. */
        fun loadSecretKey(): SecretKey? = keystore().getKey(KEY_ALIAS, null) as SecretKey?

        /**
         * Whether the key demands user presence on each use. Exposed so the
         * trade documented above is asserted rather than assumed.
         */
        fun keyRequiresUserAuthentication(): Boolean {
            val key = loadSecretKey() ?: return false
            val factory = javax.crypto.SecretKeyFactory.getInstance(key.algorithm, KEYSTORE)
            val info = factory.getKeySpec(key, android.security.keystore.KeyInfo::class.java)
            return (info as android.security.keystore.KeyInfo).isUserAuthenticationRequired
        }
    }
}
